baseURL: http://example.org/
languageCode: id
title: 2mata
copyright: "[2mata.github.io](/)"
theme: hyde


enableEmoji: true
paginate: 1


markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
      wrapStandAloneImageWithinParagraph: false
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  

minify:
  tdewolff:
    html:
      keepQuotes: true

taxonomies:
  tag: tags
  author: author



related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
  - name: title
    weight: 100
  - name: keywords
    weight: 100
  - name: date
    weight: 100


Menus:
  main:
    - Name: "Tentang Kami"
      URL: "/about/"
    - Name: "Disclaimer"
      URL: "/disclaimer/"
    - Name: "Privacy Police"
      URL: "/privacy-policy/"
    - Name: "Jasa Sadap iPhone"
      URL: "/blog/aplikasi-penyadap-hp/"
    - Name: "Jasa Sadap Android"
      URL: "/blog/aplikasi-sadap-hp/"
    - Name: "Sitemap"
      URL: "/sitemap-html/"

params: